# Generated by Django 5.2.8 on 2025-11-18 23:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Profissional',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Serviço')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duração padrão')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor padrão')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.company')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ncalendar.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['professional', 'name'],
                'unique_together': {('company', 'professional', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Início')),
                ('end', models.DateTimeField(editable=False, verbose_name='Fim')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Agendado'), (2, 'Concluído'), (3, 'Cancelado'), (4, 'Não compareceu'), (6, 'Em andamento'), (7, 'Pendente pagamento')], default=1, verbose_name='Status')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600), verbose_name='Duração real')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor cobrado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncalendar.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncalendar.professional', verbose_name='Profissional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ncalendar.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'ordering': ['-start'],
                'indexes': [models.Index(fields=['start', 'professional'], name='ncalendar_e_start_37d50f_idx'), models.Index(fields=['status'], name='ncalendar_e_status_9992bc_idx')],
            },
        ),
    ]
