# Generated by Django 5.0.6 on 2025-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
