# Generated by Django 5.0.6 on 2025-11-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncalendar', '0002_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone'),
        ),
    ]
